# Generated by Django 4.1 on 2023-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='BMI',
        ),
        migrations.AddField(
            model_name='food',
            name='BMI',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodlog',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='BMR',
            field=models.FloatField(),
        ),
    ]
