# Generated by Django 4.1 on 2023-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_remove_food_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='allergies',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
