# Generated by Django 4.1 on 2023-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_blood_remove_userdetails_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='mobile',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
