# Generated by Django 4.1 on 2024-01-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0010_remove_food_preparation_alter_food_allergies_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
