# Generated by Django 4.1 on 2024-01-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_rename_steps_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='diet.food')),
            ],
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='food',
            name='steps',
            field=models.ManyToManyField(related_name='food_steps', to='diet.steps'),
        ),
    ]
