# Generated by Django 4.1 on 2024-02-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0016_alter_restaurant_foods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='foods',
            new_name='food',
        ),
    ]
