# Generated by Django 4.1 on 2024-02-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0017_rename_foods_restaurant_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='steps',
        ),
        migrations.AddField(
            model_name='food',
            name='Peparation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='diet.ingredient'),
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
