# Generated by Django 4.1 on 2024-02-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0018_remove_food_steps_food_peparation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diet.food'),
            preserve_default=False,
        ),
    ]
