# Generated by Django 4.1 on 2024-02-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0019_remove_restaurant_food_restaurant_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='food',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food',
            field=models.ManyToManyField(related_name='restaurants', to='diet.food'),
        ),
    ]
