# Generated by Django 4.1 on 2024-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0020_remove_restaurant_food_restaurant_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='diet.foodcategory'),
        ),
    ]
