# Generated by Django 4.1 on 2024-02-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0021_remove_food_category_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(null=True, to='diet.foodcategory'),
        ),
    ]
