# Generated by Django 4.1 on 2024-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0022_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, to='diet.foodcategory'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='diet.ingredient'),
        ),
    ]
