# Generated by Django 4.1 on 2024-02-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0024_food_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Peparation',
            new_name='Preparation',
        ),
    ]
