# Generated by Django 4.1 on 2024-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0025_rename_peparation_food_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=30),
        ),
    ]
