# Generated by Django 4.1 on 2024-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0026_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='BMI',
            field=models.FloatField(default=31.21),
            preserve_default=False,
        ),
    ]
