# Generated by Django 4.1 on 2024-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0029_rename_goal_userdetails_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='goal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
