# Generated by Django 4.1 on 2024-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0030_alter_userdetails_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='goal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
