# Generated by Django 4.1 on 2024-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0031_alter_food_goal_delete_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='goal',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Weight Maintain', 'Weight Maintain')], max_length=20),
        ),
    ]
