# Generated by Django 4.1 on 2024-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0032_alter_food_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
